-- MySQL Script generated by MySQL Workbench
-- Mon Aug 26 19:19:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema livetutoring
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema livetutoring
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `livetutoring` DEFAULT CHARACTER SET utf8 ;
USE `livetutoring` ;

-- -----------------------------------------------------
-- Table `livetutoring`.`classdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livetutoring`.`classdetail` (
  `idclassDetail` INT(11) NOT NULL AUTO_INCREMENT,
  `className` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `createdAt` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idclassDetail`),
  INDEX `className_idx` (`className` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `livetutoring`.`classchapter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livetutoring`.`classchapter` (
  `idchapter` INT(11) NOT NULL AUTO_INCREMENT,
  `chapterName` VARCHAR(45) NOT NULL,
  `classId` INT(11) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idchapter`),
  INDEX `idclassDetail_idx` (`classId` ASC) VISIBLE,
  CONSTRAINT `idclassDetail`
    FOREIGN KEY (`classId`)
    REFERENCES `livetutoring`.`classdetail` (`idclassDetail`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `livetutoring`.`chaptertopic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livetutoring`.`chaptertopic` (
  `idchapterTopic` INT(11) NOT NULL AUTO_INCREMENT,
  `topicName` VARCHAR(45) NOT NULL,
  `chapterId` INT(11) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idchapterTopic`),
  INDEX `idchapter_idx` (`chapterId` ASC) VISIBLE,
  INDEX `topicName_idx` (`topicName` ASC) VISIBLE,
  CONSTRAINT `idchapter`
    FOREIGN KEY (`chapterId`)
    REFERENCES `livetutoring`.`classchapter` (`idchapter`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `livetutoring`.`gameinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livetutoring`.`gameinfo` (
  `idgameInfo` INT(11) NOT NULL AUTO_INCREMENT,
  `gameUrl` VARCHAR(45) NOT NULL,
  `gameName` VARCHAR(200) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idgameInfo`),
  INDEX `gameName_idx` (`gameName` ASC) INVISIBLE,
  INDEX `gameUrl_idx` (`gameUrl` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `livetutoring`.`videoinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livetutoring`.`videoinfo` (
  `idvideoInfo` INT(11) NOT NULL AUTO_INCREMENT,
  `videoName` VARCHAR(200) NOT NULL,
  `videoPath` VARCHAR(200) NOT NULL,
  `playerName` VARCHAR(200) NOT NULL,
  `playerPath` VARCHAR(200) NOT NULL,
  `videoLength` VARCHAR(200) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idvideoInfo`),
  INDEX `videoName_idx` (`videoName` ASC) VISIBLE,
  INDEX `videoPath_idx` (`videoPath` ASC) INVISIBLE,
  INDEX `playerName_idx` (`playerName` ASC) INVISIBLE,
  INDEX `playerPath_idx` (`playerPath` ASC) VISIBLE,
  INDEX `videoLength_idx` (`videoLength` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `livetutoring`.`chaptersubtopic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livetutoring`.`chaptersubtopic` (
  `idchapterSubTopic` INT(11) NOT NULL AUTO_INCREMENT,
  `subtopicName` VARCHAR(45) NOT NULL,
  `startTime` INT(11) NOT NULL,
  `stopTime` INT(11) NOT NULL,
  `gameId` INT(11) NOT NULL,
  `videoId` INT(11) NOT NULL,
  `chapterTopicId` INT(11) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idchapterSubTopic`),
  INDEX `idchapterTopic_idx` (`chapterTopicId` ASC) VISIBLE,
  INDEX `idvideoInfo_idx` (`videoId` ASC) VISIBLE,
  INDEX `idgameInfo_idx` (`gameId` ASC) VISIBLE,
  INDEX `subtopic_idx` (`subtopicName` ASC) VISIBLE,
  CONSTRAINT `idchapterTopic`
    FOREIGN KEY (`chapterTopicId`)
    REFERENCES `livetutoring`.`chaptertopic` (`idchapterTopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idgameInfo`
    FOREIGN KEY (`gameId`)
    REFERENCES `livetutoring`.`gameinfo` (`idgameInfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idvideoInfo`
    FOREIGN KEY (`videoId`)
    REFERENCES `livetutoring`.`videoinfo` (`idvideoInfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `livetutoring`.`userauth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livetutoring`.`userauth` (
  `iduserAuth` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `logincount` VARCHAR(45) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `blockStatus` ENUM('block', 'unblock') NOT NULL,
  PRIMARY KEY (`iduserAuth`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `livetutoring`.`classenrollments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livetutoring`.`classenrollments` (
  `idclassEnrollments` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL,
  `classId` INT(11) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idclassEnrollments`),
  INDEX `iduserAuth_idx` (`userId` ASC) VISIBLE,
  INDEX `idclassDetail_idx` (`classId` ASC) VISIBLE,
  CONSTRAINT `authUserId`
    FOREIGN KEY (`userId`)
    REFERENCES `livetutoring`.`userauth` (`iduserAuth`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `classUserId`
    FOREIGN KEY (`classId`)
    REFERENCES `livetutoring`.`classdetail` (`idclassDetail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `livetutoring`.`classtiming`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livetutoring`.`classtiming` (
  `idclassTiming` INT(11) NOT NULL AUTO_INCREMENT,
  `startTime` TIMESTAMP NULL,
  `endTime` TIMESTAMP NULL,
  `classEnrollMent` INT(11) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idclassTiming`),
  INDEX `idclassEnrollments_idx` (`classEnrollMent` ASC) VISIBLE,
  CONSTRAINT `idclassEnrollments`
    FOREIGN KEY (`classEnrollMent`)
    REFERENCES `livetutoring`.`classenrollments` (`idclassEnrollments`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `livetutoring`.`studentlicense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livetutoring`.`studentlicense` (
  `idstudentLicense` INT(11) NOT NULL AUTO_INCREMENT,
  `licenseId` VARCHAR(45) NOT NULL,
  `studentId` INT(11) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idstudentLicense`),
  INDEX `iduserAuth_idx` (`studentId` ASC) VISIBLE,
  UNIQUE INDEX `licenseId_UNIQUE` (`licenseId` ASC) VISIBLE,
  CONSTRAINT `studentUserAuthId`
    FOREIGN KEY (`studentId`)
    REFERENCES `livetutoring`.`userauth` (`iduserAuth`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `livetutoring`.`studentenrollinclass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livetutoring`.`studentenrollinclass` (
  `idstudentEnrollinClass` INT(11) NOT NULL,
  `studentLicId` INT(11) NOT NULL,
  `classTimingId` INT(11) NOT NULL,
  `createdAt` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idstudentEnrollinClass`),
  INDEX `idclassTiming_idx` (`classTimingId` ASC) VISIBLE,
  INDEX `idstudentLicense_idx` (`studentLicId` ASC) VISIBLE,
  CONSTRAINT `idclassTiming`
    FOREIGN KEY (`classTimingId`)
    REFERENCES `livetutoring`.`classtiming` (`idclassTiming`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `studentLicenseId`
    FOREIGN KEY (`studentLicId`)
    REFERENCES `livetutoring`.`studentlicense` (`idstudentLicense`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `livetutoring`.`userdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livetutoring`.`userdetail` (
  `iduserDetail` INT(11) NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `dob` DATETIME NOT NULL,
  `acedemicYear` INT(11) NOT NULL,
  `mobile` VARCHAR(10) NOT NULL,
  `createdat` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `roleName` ENUM('Teacher', 'Student', 'Admin', 'SuperAdmin') NOT NULL,
  PRIMARY KEY (`iduserDetail`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE,
  INDEX `firstName` (`firstName` ASC) INVISIBLE,
  INDEX `mobile_idx` (`mobile` ASC) VISIBLE,
  CONSTRAINT `iduserAuth`
    FOREIGN KEY (`iduserDetail`)
    REFERENCES `livetutoring`.`userauth` (`iduserAuth`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `livetutoring`.`gameScore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livetutoring`.`gameScore` (
  `idgameScore` INT NOT NULL,
  `gameid` INT NOT NULL,
  `studentId` INT NOT NULL,
  `studentScore` JSON NOT NULL,
  `classId` INT NOT NULL,
  `createdAt` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idgameScore`),
  INDEX `studentplayGame_idx` (`gameid` ASC) VISIBLE,
  INDEX `studentId _idx` (`studentId` ASC) VISIBLE,
  INDEX `studentclassId_idx` (`classId` ASC) VISIBLE,
  CONSTRAINT `studentplayGame`
    FOREIGN KEY (`gameid`)
    REFERENCES `livetutoring`.`gameinfo` (`idgameInfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `studentId `
    FOREIGN KEY (`studentId`)
    REFERENCES `livetutoring`.`userauth` (`iduserAuth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `studentclassId`
    FOREIGN KEY (`classId`)
    REFERENCES `livetutoring`.`classdetail` (`idclassDetail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `livetutoring`;

DELIMITER $$
USE `livetutoring`$$
CREATE DEFINER = CURRENT_USER TRIGGER `livetutoring`.`userauth_BEFORE_INSERT` BEFORE INSERT ON `userauth` FOR EACH ROW
BEGIN
IF NEW.`email` NOT LIKE '%_@%_.__%' THEN
		SIGNAL SQLSTATE VALUE '45000'
			SET MESSAGE_TEXT = '[table:userauth] - `email` column is not valid';
	END IF;
END$$

USE `livetutoring`$$
CREATE DEFINER = CURRENT_USER TRIGGER `livetutoring`.`studentenrollinclass_BEFORE_INSERT` BEFORE INSERT ON `studentenrollinclass` FOR EACH ROW
BEGIN


END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
